name: CI

on:
  push:
    branches: [ main ]
    paths:
      - traits/**/*.png

  workflow_dispatch:

jobs:
  rle:
    runs-on: ubuntu-latest
    steps:
      - name: output existing color palette
        id: existing-palette
        run: echo "::set-output name=colors::$(jq .palette existing-palette.json)"
      - uses: actions/checkout@v2
      - uses: solimander/nounish-rle-action@v1.0.0-alpha.3
        with:
          rootDirectoryPath: traits
          outputPath: image-data.json
          existingPalette: ${{ join(steps.existing-palette.outputs.colors) }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add image-data.json
          git commit -m "Update run-length encoded image data"
          git push origin main
